#!/usr/bin/env python3

import unicodedata
from pathlib import Path

UNICODE_LIMIT = 0x110000
BLOCK_SIZE = 0x100
BLOCK_COUNT = UNICODE_LIMIT // BLOCK_SIZE


def build_ranges():
    ranges = []
    start = None

    for c in range(UNICODE_LIMIT):
        is_punctuation = unicodedata.category(chr(c)).startswith("P")

        if is_punctuation and start is None:
            start = c
        elif not is_punctuation and start is not None:
            ranges.append((start, c - 1))
            start = None

    if start is not None:
        ranges.append((start, UNICODE_LIMIT - 1))

    return ranges


def build_block_index(ranges):
    first = [0] * BLOCK_COUNT
    count = [0] * BLOCK_COUNT

    for i, (lo, hi) in enumerate(ranges):
        first_block = lo // BLOCK_SIZE
        last_block = hi // BLOCK_SIZE

        for block in range(first_block, last_block + 1):
            if count[block] == 0:
                first[block] = i
            count[block] += 1

    return first, count


def emit_array(out, name, c_type, values, columns=8):
    out.write(f"static const {c_type} {name}[{len(values)}] = {{\n")

    for i in range(0, len(values), columns):
        values_line = ", ".join(f"0x{x:X}" for x in values[i : i + columns])
        out.write(f"\t{values_line},\n")

    out.write("};\n\n")


def main():
    ranges = build_ranges()
    first, count = build_block_index(ranges)

    ascii_bits = 0

    for c in range(0x80):
        if unicodedata.category(chr(c)).startswith("P"):
            ascii_bits |= 1 << c

    output = Path(__file__).parent.parent / "src" / "unicode_data.inc"

    with output.open("w") as out:
        out.write("/* Generated by scripts/generate_unicode.py. Do not edit. */\n\n")

        out.write("static const uint64_t unicode_punctuation_ascii[2] = {\n")
        out.write(f"\tUINT64_C(0x{ascii_bits & 0xFFFFFFFFFFFFFFFF:016X}),\n")
        out.write(f"\tUINT64_C(0x{ascii_bits >> 64:016X}),\n")
        out.write("};\n\n")

        out.write("static const UnicodeRange unicode_punctuation[] = {\n")

        for lo, hi in ranges:
            out.write(f"\t{{0x{lo:06X}, 0x{hi:06X}}},\n")

        out.write("};\n\n")

        emit_array(
            out,
            "unicode_punctuation_first",
            "uint16_t",
            first,
        )

        emit_array(
            out,
            "unicode_punctuation_count",
            "uint8_t",
            count,
        )


if __name__ == "__main__":
    main()
